---
- name: Redis | Copy charts to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "{{ local_bundle_dir }}/redis-{{ redis_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Redis | Copy manifests to k3s dir
  become: true
  ansible.builtin.template:
    src: "../templates/redis.yaml.j2"
    dest: "{{ k3s_manifests_dir }}/redis.yaml"