---
- name: Generate Inventory
  hosts: localhost
  vars:
    config_dir: "{{ lookup('ansible.builtin.env', 'INVENTORY') }}"
  tasks:
  - name: Ensure Inventory Dir exists
    ansible.builtin.file:
      path: "{{ config_dir }}"
      state: directory

  - name: Copy inventory template file
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/inventory/{{ item }}"
      dest: "{{ config_dir }}/{{ item }}"
      force: false
      follow: true
    with_items:
      - hosts.yaml
      - globals.yaml

  - name: Check if secrets file exists
    ansible.builtin.stat:
      path: "{{ config_dir }}/secrets.yaml"
    register: secrets_file_exists

  - name: Include secrets file
    ansible.builtin.include_vars:
      dir: "{{ config_dir }}"
      files_matching: secrets.yaml
    when: secrets_file_exists.stat.exists

  - name: Generate random secrets for the components
    ansible.builtin.template:
      src: "{{ playbook_dir }}/inventory/secrets.yaml.j2"
      dest: "{{ config_dir }}/secrets.yaml"

  - name: Encrypt secrets.yaml with current Vault key
    ansible.builtin.shell:
      chdir: "{{ config_dir }}"
      # we expect to have ANSIBLE_VAULT_PASSWORD_FILE to be exported already
      cmd: |
         ansible-vault encrypt --output {{ config_dir }}/secrets.yaml secrets.yaml