---
- name: Install kubernetes 
  hosts: controllers
  tasks:
    - block:
        - name: k3s | Install
          vars:
            role_action: "{{ item }}"
          include_role:
            name: k3s
            apply:
              tags:
                - k3s
          tags:
            - always
          with_items:
            - ["prereq", "install"]
      rescue:
        - name: install k3s errors
          ansible.builtin.fail:
            msg: 'Error during {{ ansible_failed_task.name }}. Please run: make install OPTS="--tags k3s"'

- name: Install Other Components
  hosts: controllers
  tasks:
    - block:
        - name: Cert-manager | Install
          vars:
            role_action: "{{ item.0 }}"
          include_role:
            name: "{{ item.1 }}"
            apply:
              tags:
                - base
          tags:
            - always
          with_nested:
            - ["install", "post-install"]
            - ["cert-manager"]
      rescue:
        - name: install Base errors
          ansible.builtin.fail:
            msg: 'Error during {{ ansible_failed_task.name }}. Please run: make install OPTS="--skip-tags k3s" '

