---
- name: Stack Deployer Pre-requisites
  hosts: all
  block:
    - name: k3s | Pre-requisites
      tasks:
        - import_role:
            name: k3s
            tasks_from: prereq
    - name: Cert-manager | Pre-requisites
      tasks:
        - import_role:
            name: cert-manager
            tasks_from: prereq
      when: enable_cert_manager

