---
- name: Pre-Requisites Kubernetes
  hosts: controllers
  vars:
    role_action: "prereq"
  tasks:
    - block:
        - include_role:
            name: k3s
            apply:
              tags:
                - k3s
          tags:
            - always
      rescue:
        - name: Pre-Requisites k3s errors
          ansible.builtin.fail:
            msg: 'Error during {{ ansible_failed_task.name }}. Please run: make pre-requisites OPTS="--tags k3s" '