---
- name: Install tools for security assessment 
  hosts: controllers
  tasks:
    - block:
        - name: sec-assessment | Install
          vars:
            role_action: "{{ item }}"
          include_role:
            name: k8s-sec-assessment/roles/sec-assessment
            apply:
              tags:
                - security_install
          tags:
            - always
          with_items:
            - ["install"]
      rescue:
        - name: Install tools errors
          ansible.builtin.fail:
            msg: 'Error during {{ ansible_failed_task.name }}. Please run: make install OPTS="--tags security_install"'

- name: Execute the security assessment 
  hosts: controllers
  tasks:
    - block:
        - name: sec-assessment | execution
          vars:
            role_action: "{{ item }}"
          include_role:
            name: k8s-sec-assessment/roles/sec-assessment
            apply:
              tags:
                - security_exec
          tags:
            - always
          with_items: 
            - ["execute"]
      rescue:
        - name: Install tools errors
          ansible.builtin.fail:
            msg: 'Error during {{ ansible_failed_task.name }}. Please run: make execute OPTS="--tags security_exec"'
