---
- name: Stack Deployer Uninstall
  hosts: controllers
  tasks:
    - block:
        - name: k3s | Install
          vars:
            role_action: "uninstall"
          include_role:
            name: k3s
            apply:
              tags:
                - k3s
          tags:
            - always