---
- name: Cert-manager | Copy manifests to k3s dir
  become: true
  ansible.builtin.template:
    src: "../templates/cert-manager.yaml.j2"
    dest: "{{ k3s_manifests_dir }}/cert-manager.yaml"

- name: Cert-manager | Copy CRD's manifest to k3s dir
  become: true
  ansible.builtin.copy:
    src: "../files/cert-manager.crds.yaml"
    dest: "{{ k3s_manifests_dir }}/cert-manager-crds.yaml"