---
- name: Monitoring | Copy charts to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "../files/kube-prometheus-stack-{{ monitoring_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Monitoring | Copy manifests to k3s dir
  become: true
  ansible.builtin.template:
    src: "../templates/monitoring.yaml.j2"
    dest: "{{ k3s_manifests_dir }}/monitoring.yaml"