---
- name: Logging | Copy rancher logging charts to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "../files/rancher-logging-chart-{{ rancher_logging_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Logging | Copy rancher logging crds to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "../files/rancher-logging-crd-{{ rancher_logging_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Elastic | Copy elastic charts to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "../files/elasticsearch-{{ elastic_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Kibana | Copy kibana charts to k3s charts dir
  become: true
  ansible.builtin.copy:
    src: "../files/kibana-{{ kibana_version }}.tgz"
    dest: "{{ k3s_charts_dir }}"

- name: Logging | Copy manifests to k3s dir
  become: true
  ansible.builtin.template:
    src: "../templates/logging.yaml.j2"
    dest: "{{ k3s_manifests_dir }}/logging.yaml"