---
- name: k3s | Install K3s first master
  when: inventory_hostname == groups['controllers'][0]
  block:
  - name: k3s | Copy k3s config file
    become: true
    template:
      src: ../templates/config.yaml.j2
      dest: /etc/rancher/k3s/config.yaml
      mode: 0644

  - name: k3s | Install K3s first master
    become: true
    shell:
      cmd: "INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server' K3S_KUBECONFIG_MODE='644' ./install.sh  --disable servicelb"
      chdir: "/etc/rancher/k3s/"
    ignore_errors: true
    async: 600
    poll: 5
    
  - name: k3s | Get k3s token
    become: true
    command: "cat /var/lib/rancher/k3s/server/token"
    register: token

  - name: k3s | Print the k3s token
    debug:
      msg: "The generated token is {{ token.stdout }}"

  - name: k3s | Create .kube directory
    ansible.builtin.file:
      state: directory
      path: "/home/{{ ansible_user }}/.kube"

  - name: k3s | Copy the kubeconfig to the .kube directory
    become: true
    ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: "/home/{{ ansible_user }}/.kube/config"
      remote_src: true
      mode: 0644

- name: k3s | Install K3s other masters
  when: inventory_hostname != groups['controllers'][0]
  block:
  - name: Copy k3s config file
    become: true
    template:
      src: ../templates/config-other-master.yaml.j2
      dest: /etc/rancher/k3s/config.yaml
      mode: 0644

  - name: Install K3s
    become: true
    shell:
      cmd: "INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --server https://{{ hostvars['vm-1']['ansible_host'] }}:6443' ./install.sh --disable servicelb"
      chdir: "/etc/rancher/k3s/"
    ignore_errors: true
    async: 600
    poll: 5

  - name: Create .kube directory
    ansible.builtin.file:
      state: directory
      path: "/home/{{ ansible_user }}/.kube"

  - name: Copy the kubeconfig to the .kube directory
    become: true
    ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: "/home/{{ ansible_user }}/.kube/config"
      remote_src: true
      mode: 0644