---
- name: k3s | Create temporary K9s directory
  ansible.builtin.file:
    state: directory
    path: "/tmp/k9s"

- name: k3s | Unpack K9s
  ansible.builtin.unarchive:
    src: "{{ local_bundle_dir }}/k9s_Linux.tar.gz"
    dest: "/tmp/k9s"

- name: k3s | Install K9s
  become: true
  ansible.builtin.copy:
    src: "/tmp/k9s/k9s"
    dest: "/usr/bin/k9s"
    mode: "+x"
    remote_src: true

- name: k3s | Cleaning Up temporary K9s installation files
  become: true
  ansible.builtin.file:
    path: "/tmp/{{ k9s }}"
    state: absent
  loop_control:
    loop_var: k9s
  with_items:
    - "k9s_Linux.tar.gz"
    - "k9s"
  
- name: k3s | Ensure the k3s config directory exists
  become: true
  ansible.builtin.file:
    path: "/etc/rancher/k3s/"
    state: "directory"
    mode: "+x"

- name: k3s | Copy install.sh 
  become: true
  ansible.builtin.copy:
    src: "{{ local_bundle_dir }}/install.sh"
    dest: "/etc/rancher/k3s/install.sh"
    mode: "+x"

- name: k3s | Ensure the k3s manifests directory exists
  become: true
  ansible.builtin.file:
    path: "{{ k3s_manifests_dir }}"
    state: "directory"
    mode: "+x"

- name: k3s | Place the k3s binary at /usr/local/bin/k3s and ensure it is executable
  become: true
  ansible.builtin.copy:
    src: "{{ local_bundle_dir }}/k3s"
    dest: "/usr/local/bin/k3s"
    mode: "+x"

- name: k3s | Ensure the k3s images directory exists
  become: true
  ansible.builtin.file:
    path: "{{ k3s_images_dir }}"
    state: "directory"
    mode: "+x"

- name: k3s | Place the images tar file in the images directory
  become: true
  ansible.builtin.unarchive:
    src: "{{ local_bundle_dir }}/k3s-airgap-images.tar.gz"
    dest: "{{ k3s_images_dir }}"

- name: k3s | Stop firewall service
  become: true
  ansible.builtin.systemd:
    name: ufw
    state: stopped

- name: k3s | Copy the bundled manifest to the k3s manifest directory
  become: true
  ansible.builtin.copy:
    src: "{{ local_bundle_manifests_dir }}/"
    dest: "{{ k3s_manifests_dir }}"
    mode: "0644"

- name: OS Settings
  block:
    - name: Disable swap temporarily
      become: true
      command: swapoff -a
      ignore_errors: true

    - name: Remove swap from fstab
      become: true
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+){2}swap\s+'
        replace: '#\1swap    '
        backup: yes

    - name: Ensure changes are persistent
      become: true
      lineinfile:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+){2}swap\s+'
        state: absent

- name: Install pip and kubernetes python module
  ansible.builtin.package:
    name: 
      - python3
      - python3-pip
      - python3-kubernetes
    state: present
  become: true

- name: Install dnsmasq
  ansible.builtin.package:
    name: dnsmasq
    state: present
  become: true

- name: Configure dnsmasq
  become: true
  ansible.builtin.template:
    src: "../templates/dnsmasq.conf.j2"
    dest: /etc/dnsmasq.conf
