---
- name: Configure Vault
  block:
    - name: Get secret from Kubernetes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: vault-keys
        namespace: vault
      register: secret_output

    - name: Vault login
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault login {{ secret_output.resources[0].data.token | b64decode }}

    - name: Vault enable secrets transit
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault secrets enable transit

    - name: Write config
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault write /transit/keys/git-safe -type=rsa-4096

    - name: Read HCL file
      slurp:
        src: "{{ playbook_dir }}/roles/vault/files/config.hcl"
      register: hcl_file

    - name: Write policy
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault policy write transit-policy {{ hcl_file.content | b64decode }}

    - name: Vault enable approle
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault enable approle

    - name: Write approle config
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault write auth/approle/role/git-secrets token_ttl=5m token_max_ttl=10m token_type=default policies=”transit-policy”

    - name: Read approle config
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault read /auth/approle/role/git-secrets/role-id
      register: role-id

    - name: Vault write secret-id
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: vault write -force /auth/approle/role/git-secrets/secret-id
      register: secret-id
  tags:
    - configure