---
- name: Apply Vault Helm chart
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: vault
    create_namespace: true
    values:
      server:
        dataStorage:
          enabled: true
          storageClass: local-path
        affinity: {}
        tolerations: []
    state: present
    kubeconfig: ~/.kube/config

- name: Wait for Vault pod to be in Running status
  kubernetes.core.k8s_info:
    kubeconfig: ~/.kube/config
    api_version: v1
    kind: Pod
    namespace: vault
  register: vault_pod 
  until: vault_pod | json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 10

- name: Create NodePort service for Vault
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: vault-nodeport
        namespace: vault
      spec:
        type: NodePort
        selector:
          app: vault
        ports:
          - protocol: TCP
            port: 8200
            targetPort: 8200
            nodePort: 30080