---
- name: Exchange SSH keys
  hosts: controllers
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
        type: rsa
        size: 2048
      register: ssh_keypair
      ignore_errors: yes

    - name: Ensure .ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Read public key
      slurp:
        src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
      register: public_key_content

    - name: Copy public key to remote server
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key_content.content | b64decode }}"
