---
- name: Exchange SSH keys
  hosts: all
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
        type: rsa
        size: 2048
      register: ssh_keypair
      ignore_errors: yes

    - name: Ensure .ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Copy public key to remote server
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', ssh_keypair.public_key) }}"
