---
- name: Install k3d cluster and tools
  hosts: localhost
  tasks:
    - name: k3d | Install
      vars:
        role_action: "install"
      include_role:
        name: k3d
        apply:
          tags:
            - k3d
      tags:
        - always

    - name: Vault | Install
      vars:
        role_action: "{{ item }}"
      include_role:
        name: vault
        apply:
          tags:
            - vault
      tags:
        - always
      with_items:
        - ["install", "bootstrap", "configure"]
