---
- name: Uninstall k3d cluster 
  hosts: localhost
  tasks:
    - name: k3d | Uninstall
      vars:
        role_action: "uninstall"
      include_role:
        name: k3d
        apply:
          tags:
            - k3d
      tags:
        - always

    - name: Vault | Uninstall
      vars:
        role_action: "uninstall"
      include_role:
        name: vault
        apply:
          tags:
            - vault
      tags:
        - always


