---
- name: Cert-manager | Download cert-manager crds
  ansible.builtin.get_url:
    url: "{{ cert_manager_crds_url }}"
    dest: "{{ local_bundle_manifests_dir }}/cert-manager-crds.yaml"
    mode: "+x"
    validate_certs: false