---
- name: Download cert_manager manifests
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
    mode: "0644"
  with_items: 
    - "{{ cert_manager_crds_url }}"
  when: components.cert_manager is true

- name: Move cert_manager manifests to the local temporary bundled manifests directory
  ansible.builtin.copy:
    src: "../files/{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
  delegate_to: localhost
  with_items: 
    - "cert-manager.yaml"
  when: components.cert_manager is true
