---
- name: Cert-manager | Download cert_manager manifests
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ local_bundle_manifests_dir }}/"
    mode: "0644"
  with_items: 
    - "{{ cert_manager_crds_url }}"
