---
- name: k3s | Download k3s binary
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url }}"
    dest: "{{ local_bundle_dir }}/k3s"
    mode: "+x"

- name: k3s | Download k3s images
  ansible.builtin.get_url:
    url: "{{ k3s_airgap_images_url }}"
    dest: "{{ local_bundle_dir }}/k3s-airgap-images.tar.gz"
    mode: "0644"

- name: k3s | Download k3s install script
  ansible.builtin.get_url:
    url: "{{ k3s_install_script }}"
    dest: "{{ local_bundle_dir }}/install.sh"
    mode: "+x"